apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}
  annotations:
    reloader.stakater.com/auto: "true"
  name: {{ .Release.Name }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}
          name: {{ .Release.Name }}
          env:
            {{- if .Values.environment }}
              {{- range $key, $value := .Values.environment }}
            - name: {{ $key | upper }}
              value: {{ $value }}
              {{- end }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
