apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
spec:
  mode: daemonset # Choose how to deploy the collector, cf https://github.com/open-telemetry/opentelemetry-operator/blob/main/README.md#deployment-modes
  image: otel/opentelemetry-collector-contrib:0.131.0
  config:
    receivers: # How to recieve Open Telemetry data.
      otlp:
        protocols:
          grpc: {}
          http: {}

    exporters: # Where to export Open Telemetry data.
      otlp/signoz:
        endpoint: signoz-otel-collector.observability:4317
        tls:
          insecure: true

    service: # Configure each pipeline of Open Telemetry data.
      pipelines:
        logs:
          receivers: [otlp]
          exporters: [otlp/signoz]
        traces:
          receivers: [otlp]
          exporters: [otlp/signoz]
        metrics:
          receivers: [otlp]
          exporters: [otlp/signoz]
